### ISSUE TITLE
Sample error

### ISSUE THREAD

**Issue by imbolc** [yoavaviram/python-google-spreadsheet#2]
> worksheets = spreadsheet.list_worksheets(spreadsheets[0][1])

worksheets = api.list_worksheets(spreadsheets[0][1])

**Comment by imbolc** [comment]
> sheet = spreadsheet.get_worksheet('tkZQWzwHEjKTWFFCAgw', 'od7')

sheet = api.get_worksheet('tkZQWzwHEjKTWFFCAgw', 'od7')

**Comment by yoavaviram** [comment]
This was a documentation problem, which i now fixed. Thank you for pointing this out.
