### ISSUE TITLE
row header lost it's underscore

### ISSUE THREAD

**Issue by AlwaysTraining** [yoavaviram/python-google-spreadsheet#7]
I have a spreadsheet, where the first row are the labels for the columns.  Many of my labels contain underscores like "failures_today"

When I try to edit that value with:
row['failures_today'] = 1
I get a key error, and if I print out the row dictionary to string, I see that the key is now
"failurestoday"

I need to maintain my column names.  Do you ahve any suggestions

**Comment by yoavaviram** [comment]
This is the behavior of the Google Spreadsheet API. There's nothing I can do to change it...sorry.

**Comment by AlwaysTraining** [comment]
I understand, I really like your library, but have I already have some code written against the straight google api that works, I suppose I accidentally worked around the issue when I wrote my handling.  Your library is much better, and I will use it next time.

**Comment by yoavaviram** [comment]
Please share your workaround with me. I may be able to integrate it
somehow.

**Comment by AlwaysTraining** [comment]
One of the simplest things you may do is to add some kind of index based column retrieval.  If you had this users could then likely work around the issue.  But, as requested: here is some of my solution
1. as soon as you open spreadsheet, read the first row, store them in a list in memory:

```

    def query_columns(self):
        """
The text in the first row is considered to be the name of the column
"""
        query = gdata.spreadsheet.service.CellQuery()
        query.max_row = '1'
        feed = self.get_feed(query)

        cols=[]
        for entry in feed.entry:
            if entry.cell:
                cols.append(entry.cell.text)

        return cols
```
1. Construct your own dictionary object for a row when it is requested, use headers read in step 1 as the keys

```
    def get_record(self, id):
        """
Get a dictionary, keys are spreadsheet headers, values are entries
in the cell for the row specified by id
"""

        logging.debug("Reading data for: " + id)

        query = self.get_record_query(id)

        feed = self.get_feed(query)

        record = {}
        for i, entry in enumerate(feed.entry):
            if i >= len(self.ss_columns):
                raise Exception("Unknown reason for reading column: " + str(i)
                                + " : " + str(entry.cell.text) + ", for id: " +
                                str(id))

            #logging.debug("Reading column: " + self.ss_columns[i] + " : "
            # + entry.cell.text)

            if entry.cell.text is None:
                continue

            header = self.ss_columns[i]

            if is_date(entry.cell.text):
                record[header] = string_to_date(entry.cell.text)
            elif is_int(entry.cell.text):
                record[header] = int(entry.cell.text)
            elif is_float(entry.cell.text):
                record[header] = float(entry.cell.text)
            elif is_bool(entry.cell.text):
                record[header] = string_to_bool(entry.cell.text)
            else:
                record[header] = entry.cell.text

        return record
```

In your generic library I don't know if you want to get into the business of converting text to and from real types, because an application would likely need to finely control that, so you can ignore all is_some_type if statements.

**Comment by yoavaviram** [comment]
Thanks, I see how you went about it. It requires rewriting quite a bit of functionality that I get for free today using the feed API. I'm concerned of the added complexity. I don't have the time to look into this today, maybe in the future.
